# Generated by Django 4.1 on 2023-07-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_buyer_remove_user_is_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
