# Generated by Django 4.2.1 on 2023-06-01 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.URLField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('total_duration', models.IntegerField(blank=True, null=True)),
                ('to_number', models.CharField(blank=True, max_length=100, null=True)),
                ('from_number', models.CharField(blank=True, max_length=100, null=True)),
                ('call_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('transcription_gauche', models.TextField(blank=True, null=True)),
                ('transcription_droite', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(max_length=220)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='store.appel')),
            ],
        ),
    ]
