# Generated by Django 4.2.1 on 2023-06-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_appel_transcription_droite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appel',
            name='transcription_droite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appel',
            name='transcription_gauche',
            field=models.TextField(blank=True, null=True),
        ),
    ]
