# Generated by Django 4.2.1 on 2023-06-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_appel_transcription_droite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appel',
            name='left_channel',
            field=models.FileField(blank=True, null=True, upload_to='channels/'),
        ),
        migrations.AddField(
            model_name='appel',
            name='right_channel',
            field=models.FileField(blank=True, null=True, upload_to='channels/'),
        ),
        migrations.AddField(
            model_name='appel',
            name='transcription_droit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appel',
            name='transcription_gauche',
            field=models.TextField(blank=True, null=True),
        ),
    ]
