# Generated by Django 4.2.1 on 2023-06-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_appel_left_channel_appel_right_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appel',
            name='left_channel',
        ),
        migrations.RemoveField(
            model_name='appel',
            name='right_channel',
        ),
        migrations.RemoveField(
            model_name='appel',
            name='transcription_droit',
        ),
        migrations.RemoveField(
            model_name='appel',
            name='transcription_gauche',
        ),
    ]
