# Generated by Django 4.2.1 on 2023-06-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_appel_left_channel_remove_appel_right_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appel',
            name='left_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='appel',
            name='left_transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appel',
            name='right_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='appel',
            name='right_transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
