# Generated by Django 4.2.1 on 2023-06-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_appel_left_audio_appel_left_transcription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appel',
            name='left_audio',
        ),
        migrations.RemoveField(
            model_name='appel',
            name='left_transcription',
        ),
        migrations.RemoveField(
            model_name='appel',
            name='right_audio',
        ),
        migrations.RemoveField(
            model_name='appel',
            name='right_transcription',
        ),
    ]
