# Generated by Django 4.2.1 on 2023-06-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_appel_left_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appel',
            name='total_duration',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
