# Generated by Django 4.2.1 on 2023-06-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_appel_total_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
