# Generated by Django 4.2.1 on 2023-06-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powerbi_file', models.FilePathField(match='.*\\.pbix$', path='D:\\WorkSpace_Django\\pfe2023\\powerbi')),
            ],
        ),
    ]
