# Generated by Django 4.2.1 on 2023-06-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_analyses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analyses',
        ),
    ]
