# Generated by Django 4.2.1 on 2023-06-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_userprofile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
    ]
