# Generated by Django 4.2.2 on 2023-06-30 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_sentiment_converted_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentiment',
            name='converted_plot',
        ),
    ]
