# Generated by Django 4.2.2 on 2023-06-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_sentiment_converted_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='converted_plot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
