# Generated by Django 4.1 on 2023-07-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_sentiment_converted_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentiment',
            name='converted_plot',
        ),
        migrations.AddField(
            model_name='sentiment',
            name='pourcentage_negative',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='pourcentage_neutral',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='pourcentage_positive',
            field=models.FloatField(default=0),
        ),
    ]
